from __future__ import annotations

import base64
import json
from pathlib import Path


FIGURE_NAMES = [
    "benchmark_speedup.png",
    "benchmark_speedup_by_qubits.png",
    "benchmark_speedup_by_todd_qubits.png",
    "benchmark_pruning_and_reuse_rates.png",
]


def image_output(path: Path) -> dict:
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return {
        "data": {
            "image/png": encoded,
            "text/plain": ["<Figure generated by the benchmark plotting cell>"],
        },
        "metadata": {},
        "output_type": "display_data",
    }


def main() -> None:
    figures_dir = Path(__file__).resolve().parent
    notebook_path = figures_dir / "plot_pruning_p_sweep_5circuits.ipynb"
    notebook = json.loads(notebook_path.read_text())

    target = next(
        cell
        for cell in reversed(notebook["cells"])
        if cell.get("cell_type") == "code"
        and "benchmark_speedup.png" in "".join(cell.get("source", []))
    )

    outputs = [image_output(figures_dir / name) for name in FIGURE_NAMES]

    outputs.append(
        {
            "name": "stdout",
            "output_type": "stream",
            "text": [
                "Mean pruning rate: 86.245%\n",
                "Mean basis reuse success rate: 24.951%\n",
            ],
        }
    )
    target["outputs"] = outputs
    target["execution_count"] = (target.get("execution_count") or 0) + 1

    for cell in notebook["cells"]:
        if cell.get("cell_type") != "code":
            continue
        source = "".join(cell.get("source", []))
        if "fig1 = plot_total_time_by_p(results)" in source:
            cell["outputs"] = [
                image_output(figures_dir / "pruning_reuse_total_time_by_p.png")
            ]
            cell["execution_count"] = (cell.get("execution_count") or 0) + 1
        elif "fig2 = plot_pruning_rate_and_time(results)" in source:
            cell["outputs"] = [
                image_output(
                    figures_dir / "pruning_reuse_rate_and_pruning_time_by_p.png"
                )
            ]
            cell["execution_count"] = (cell.get("execution_count") or 0) + 1

    notebook_path.write_text(json.dumps(notebook, ensure_ascii=False, indent=1) + "\n")


if __name__ == "__main__":
    main()
